### ISSUE TITLE
Update to React 15.x?

### ISSUE THREAD

**Issue by smwhit** [mgechev/react-reorderable#17]
Hi - love this component - it's super simple.

Are you able to update it to the latest version of React?

Many thanks

Simon

**Comment by mgechev** [comment]
Hey @smwhit! I'll add it to my todo list for this weekend or sometime next week.

**Comment by smwhit** [comment]
Thanks @mgechev - much appreciated.

**Comment by mgechev** [comment]
Hey @smwhit, today I did some experiments. Basically the code works with React 15 but because of the method the reordering is implemented there's a warning in dev mode that the children have mutated (they are cloned). I wasn't able to come up with a trivial solution so I am planning to leave it the way it is until the projects using this library migrate to something else. Tomorrow I'll publish the packages with updated dependencies on npm.

**Comment by smwhit** [comment]
Sounds good.
Thanks!

**Comment by smwhit** [comment]
Hi @mgechev - not sure if this is working for me. 
I'm getting Peer react-reorderable@0.3.1 wants react@^0.15.0 - shouldn't that be react@^v15.0.0 ?

**Comment by mgechev** [comment]
Yes, I'll see what went wrong and republished it.
